import { AircraftConfig } from "@/types";

export const aircraftConfigs: Record<string, AircraftConfig> = {
  fighter: {
    id: "fighter",
    name: "Fighter Jet",
    description: "High-performance military aircraft with swept wings and high maneuverability",
    modelPath: "/models/fighter.dae",
    wingMeshNames: ["wing", "Wing", "wing_left", "wing_right", "wings"],
    scale: 1,
    position: [-3, 0, 0],
    fuselageLength: 1500,
    fuselageRadius: 80,
    defaultWing: {
      airfoilType: "NACA 0012",
      wingspan: 1200,
      rootChord: 400,
      tipChord: 200,
      taperRatio: 0.5,
      sweepAngle: 35,
      dihedralAngle: 0,
      nRibs: 6,
      sparCount: 2,
      hasLighteningHoles: true,
      holeRadius: 15,
      holeSpacing: 100,
      material: "Titanium 3mm",
      thickness: 3,
      color: "#9ca3af",
      opacity: 0.95,
    },
  },
  commercial: {
    id: "commercial",
    name: "Commercial Airliner",
    description: "Large passenger aircraft with high aspect ratio wings for efficiency",
    modelPath: "/models/commercial.dae",
    wingMeshNames: ["wing", "Wing", "wing_left", "wing_right", "wings"],
    scale: 1,
    position: [-3, 0, 0],
    fuselageLength: 3500,
    fuselageRadius: 200,
    defaultWing: {
      airfoilType: "NACA 2412",
      wingspan: 3600,
      rootChord: 800,
      tipChord: 400,
      taperRatio: 0.5,
      sweepAngle: 25,
      dihedralAngle: 5,
      nRibs: 12,
      sparCount: 3,
      hasLighteningHoles: true,
      holeRadius: 30,
      holeSpacing: 150,
      material: "Aluminum 2mm",
      thickness: 2,
      color: "#d8b4fe",
      opacity: 0.9,
    },
  },
  cargo: {
    id: "cargo",
    name: "Cargo Aircraft",
    description: "Heavy-lift aircraft with thick, high-lift wings for maximum payload",
    modelPath: "/models/cargo.dae",
    wingMeshNames: ["wing", "Wing", "wing_left", "wing_right", "wings"],
    scale: 1,
    position: [0, 0, 0],
    fuselageLength: 4000,
    fuselageRadius: 250,
    defaultWing: {
      airfoilType: "NACA 4415",
      wingspan: 4000,
      rootChord: 1000,
      tipChord: 600,
      taperRatio: 0.6,
      sweepAngle: 15,
      dihedralAngle: 3,
      nRibs: 14,
      sparCount: 3,
      hasLighteningHoles: true,
      holeRadius: 35,
      holeSpacing: 180,
      material: "Aluminum 4mm",
      thickness: 4,
      color: "#a7f3d0",
      opacity: 0.9,
    },
  },
};

